### ISSUE TITLE
root user is not accessible without password

### ISSUE THREAD

**Issue by paulshatalov** [suchja/wine#10]
I need to run some commands under root user, but it is requred a password.
What can I do in this case?

**Comment by suchja** [comment]
@paulshatalov How exactly are you trying to switch users and what is the exact error message?

**Comment by paulshatalov** [comment]
As sudo is not available for user xclient I'm trying switch user to root with "su" command and it requests password.
![default](https://cloud.githubusercontent.com/assets/5530873/22469606/b310a25a-e7dd-11e6-90b0-1d1a997aba79.png)

wine run string is:
docker run -it --device=/dev/ttyS0 --link display:xserver --name wine -v /home/osboxes/XMLInterface:/XMLInterface --volumes-from display  suchja/wine:latest /bin/bash'

**Comment by suchja** [comment]
So maybe [this answer on stackoverflow](http://stackoverflow.com/a/28722834/5258906) helps. It basically tells you to use a parameter `-u 0`. When this parameter is supplied to `docker run` you can start the container directly with root-priviledges.

The su-password is probably defined in the core-image, but I haven't found it yet.

Please also consider the advice given in the linked answer with regards to not switching to root-user in a running container. Not sure what exactly the risk is, but you read it a lot.

Hope this helps.

**Comment by suchja** [comment]
If you have further question please feel free to open another issue or comment on this one.
