### ISSUE TITLE
can this run windows exe command line dos?

### ISSUE THREAD

**Issue by cordoval** [suchja/wine#12]
i need to just run a cli windows exe tool that reads and outputs a file
will this image help me do that?

just curious because it is a use case. The contrary will mean that i have to run windows server and create a full microservice just to run this little stupid script.

**Comment by suchja** [comment]
Yes, generally `wine` is able to run dos scripts. However, remember it is not a fully fledged windows and this image also includes a rather old version of `wine` (currently I don't have the time to update it 😞).

If it is a simple script then you should give it a try.

**Comment by cordoval** [comment]
k thanks

**Comment by cordoval** [comment]
i tested my command and it runs on wine correctly 👍 now it is time to use this image

**Comment by suchja** [comment]
Great! Enjoy it!

**Comment by cordoval** [comment]
```
xclient@185f3531959c:/Utility Tool$ env DISPLAY=:0 wine ./HOSPICEVUT.exe /home/xclient/input.xml /output
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
```

@suchja any hints? i tried $DISPLAY but nothing comes out

**Comment by suchja** [comment]
Not really! Have you checked the instructions in the `Readme`? You Need the x11server and x11client Image if you like to go with UI. Everything should be documented in the readme. Haven‘t tried it for while now.

**Comment by cordoval** [comment]
this does not work with ui so i actually want to get rid of those warnings.

The command works but those warnings bothers me. that is all, the command is fully cli

**Comment by suchja** [comment]
I guess you tried the links for `wineconsole` and the other mentioned in section *Headless*?

I haven‘t used it without UI. So I‘m afraid I can be of no help.

**Comment by cordoval** [comment]
you were of help
thanks

**Comment by cordoval** [comment]
those links headless one of them is totally broken the other takes me to the general guide

so no luck there, for now this works
