### ISSUE TITLE
winetricks is outdated

### ISSUE THREAD

**Issue by apozzo** [suchja/wine#2]
Hi,

I'm trying a new project based on this great wine image.
I found that winetricks embbeded in this image is outdated.
now winetricks is hosted in github at https://github.com/Winetricks/winetricks

so the dockerfile should be changed that way 

 # Use latest version of winetricks from github
 RUN curl -k -SL 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' -o  /usr/local/bin/winetricks \
    && chmod +x /usr/local/bin/winetricks

Regards

**Comment by suchja** [comment]
Thanks for the hint. Fixed with commit 481e648.
