### ISSUE TITLE
most winetricks installs fails with returned status 43

### ISSUE THREAD

**Issue by apozzo** [suchja/wine#3]
Hi,

for my needs i tried to use this image as a base image.
I'm running boot2docker on windows,
Docker version 1.9.0, build 76d6bc9

I need some libs and tried to install them with up to date winetricks 

RUN wine wineboot --init \
        && /scripts/waitonprocess.sh wineserver \
        && winetricks --unattended vcrun2005\
        && /scripts/waitonprocess.sh wineserver \

it fails with message

---

 Note: command 'wine vcredist_x86.EXE /q' returned status 43.  Aborting.

---

it looked deeper adding some changes to WINDEBUG and found some messages about corrupted installer for vcrun2005

0045:Call user32.MessageBoxA(00000000,00126150 "The installation program appears to be damaged or corrupted.  Contact the vendor of this application.",0100bbb4
"Microsoft Visual C++ 2005 Redistributable (x86)",00010010) ret=0100407b

I tried to download the setup and install it manually int a RUN command but it fall in same error.
I tried both dev and latest tag.
Most of the libs I tried to install with winetricks or manually fall in the same situation.

unfortunately i'm not very experienced with wine, can you try to launch the winetricks command for vcrun2005 in a container or give me some hints to resolve this issue ?
should i look to wine64 in the image to run 32bits apps ? should I use some native dlls ?

Regards

**Comment by apozzo** [comment]
I was able to run any commands when using the x11server container.
unfortunately lots of commands just doesn't work if there is no display, even installers and msi in unattented mode.
this is annoying for my project because docker images creation just cannot be automated, I did not find any solution, I have to commit a container in which I did changes manualy :-\

**Comment by suchja** [comment]
Thanks for your feedback. Could you give some more details what you are trying to accomplish? I'm always looking for ways to improve the image.
