### ISSUE TITLE
X Error of failed request:  BadValue (integer parameter out of range for operation)

### ISSUE THREAD

**Issue by garex** [suchja/wine#8]
1. Started xserver container
2. Started wine container with links
3. Running `wine wineboot --init` I got:

```
wine: created the configuration directory '/home/xclient/.wine'
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  3 (X_ShmPutImage)
  Value in failed request:  0x140
  Serial number of failed request:  221
  Current serial number in output stream:  221
xclient@71fd08743a8c:~$ 
```

**Comment by suchja** [comment]
@garex Thanks for using this image! Have you checked whether `wine` is running or not? I experienced this error as well, but it did not seem to have any impact. See [here](https://github.com/suchja/wine#x-error--badvalue).

**Comment by suchja** [comment]
Please also see this hint from x11docker (commented on the image description on hub.docker.com):

> To X error ... Bad Value: your apps in docker try to access shared memory from X (X extension MIT-SHM). You can either allow access with docker run option --ipc=host, but this breaks container isolation. Otherwise, you should run your X server with MIT-SHM disabled ( X option -extension MIT-SHM). I solved this problem with x11docker, running a second X server without MIT-SHM (and without the need of VNC, by the way)

Haven't tried it, but might work as well.

**Comment by suchja** [comment]
If you have further questions please feel free to open a new issue.

**Comment by nevmerzhitsky** [comment]
A possible fix mentioned here https://github.com/osrf/docker_images/issues/21#issuecomment-239334515
