### ISSUE TITLE
xauth:  file /home/xclient/.Xauthority does not exist

### ISSUE THREAD

**Issue by ghazel** [suchja/wine#9]
```
Sending build context to Docker daemon 49.36 MB
Step 1 : FROM suchja/wine
latest: Pulling from suchja/wine
7ccc78f8af6d: Pull complete 
a3ed95caeb02: Pull complete 
626b97d2b791: Pull complete 
5f2df1d00555: Pull complete 
3e90a0fc812b: Pull complete 
d84d164f6531: Pull complete 
25afd892e577: Pull complete 
232ca3df96c9: Pull complete 
e5568803878c: Pull complete 
18afc465d425: Pull complete 
635bff10c272: Pull complete 
Digest: sha256:96827721f5905e26e2ba4b4f906981587f24560320d3044bae7ad09425fa6f77
Status: Downloaded newer image for suchja/wine:latest
 ---> 5dbee2d4566f
Successfully built 5dbee2d4566f
running inside docker container
xauth:  file /home/xclient/.Xauthority does not exist
xauth: (argv):1:  merge:  unable to open file /Xauthority/xserver.xauth
```

**Comment by paulshatalov** [comment]
Hello ghazel! How did you solve the issue?

**Comment by suchja** [comment]
@paulshatalov usually it indicates that either the x11server images is nor running or that it is not properly linked. Please ensure that you start the container as described in the README.

If you still have problems, please send the exact commands you type, which lead to the error.

**Comment by paulshatalov** [comment]
Thanks for reply, the issue was in connection to x11.

**Comment by ljrossi** [comment]
Having same problem ..... I follow instructions on read me.........       Paul ....what was the issue ? of conection to x11 ....how can i chek that ??

**Comment by leachimsumiri** [comment]
@suchja I seem to have the same issue with my link to x11. My x11server-container is running but when I try to run the wine container with:
_docker run --rm -it --link display:xserver --volumes-from display suchja/wine:latest /bin/bash_ 
I get the same error:
_xauth: file /home/xclient/.Xauthority does not exist_

**Comment by suchja** [comment]
@xjrimus the command looks good. Please Post the output of `docker ps -a` . Maybe there is something wrong with the running x11server-container

**Comment by leachimsumiri** [comment]
@suchja 

```
msu@u1604:~$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS                    NAMES
79c2f12dd384        c4497dbccd02        "/bin/sh -c 'apt-g..."   17 hours ago        Exited (100) 17 hours ago                            focused_wright
b5753a3bdf49        suchja/x11server    "/entrypoint.sh"         17 hours ago        Up 17 hours                 0.0.0.0:5900->5900/tcp   display
6851124e8f93        hello-world         "/hello"                 21 hours ago        Exited (0) 21 hours ago                              gracious_almeida
188740a4a475        hello-world         "/hello"                 21 hours ago        Exited (0) 21 hours ago                              frosty_kirch

```

**Comment by keroloswilliam** [comment]
the problem cause as i found so far is in /entrypoint.sh 
to be exact in this command `xauth merge /Xauthority/xserver.xauth` 
to regenerate the error from an already running container you can remove the file in 
> /home/xclient/.Xauthority 

and after re-running the command above you will get the same error but will generate the file and if you used the same command you won't get the error again 
If this has no affect on the functionality of the container we can suppress the stderr 

**Note:** I am not that good in X11 but I just wanted to post what I have found so far

**Comment by iver3on** [comment]
docker run --rm -it -v /root/zwb/testChipCloud/pythonEXE/:/xclient suchja/wine /xclient/SoC_DFX_Tool__CMD.exe 

same error:
xauth: (argv):1:  merge:  unable to open file /Xauthority/xserver.xauth

**Comment by Romain-P** [comment]
up?

**Comment by HugoDL** [comment]
Does anyone has news about this problem?

**Comment by DISC30** [comment]
I find redoing from a new terminal solves the issue.
